services:

  # ============================
  #  Google Cloud SQL Proxy
  # ============================
  cloudsql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.20.0
    container_name: cloudsql_proxy
    command: >
      --address 0.0.0.0
      --port 5432
      --credentials-file /config/key.json
      ${CLOUD_SQL_INSTANCE_NAME}
    volumes:
      - ./secrets/service-account-key.json:/config/key.json:ro
    ports:
      - "5432:5432"
    networks:
      - flybeta-network
    restart: always

  # ============================
  #  Node.js Backend (Producer)
  # ============================
  backend:
    image: flybeta-backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: backend
    ports:
      - 5000:5000
    env_file:
      - .env
    environment:
      - "NODE_ENV=development"
    networks:
      - flybeta-network
    depends_on:
      - cloudsql-proxy
      - kafka
      - kafka-ui
    volumes:
      - flags-data:/opt/flags


  # ============================
  #  Kafka Broker
  # ============================
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    user: root
    ports:
      - "9092:9092"      # internal listener
      - "9093:9093"      # controller
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LOG_DIRS: "/kafka-logs"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 20000000   # <-- 20 MB max message size
      KAFKA_REPLICA_FETCH_MAX_BYTES: 20000000  # <-- also increase replica fetch size
    volumes:
      - kafka-data:/kafka-logs
    networks:
      - flybeta-network


  # ============================
  #  Kafka UI
  # ============================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"  # access UI in browser
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""  # empty because KRaft mode
    depends_on:
      - kafka
    networks:
      - flybeta-network


  # ============================
  #  ML API (FastAPI)
  # ============================
  ml:
    image: flybeta-ml
    build:
      context: ./ml
      dockerfile: ml.dockerfile
    container_name: ml
    env_file:
      - .env
    ports:
      - "6000:6000"
    networks:
      - flybeta-network
    depends_on:
      - kafka
      - backend


  # ============================
  #  Flink Processor
  # ============================
  flink:
    build:
      context: ./flink
      dockerfile: flink.dockerfile
    container_name: flink
    env_file:
      - .env
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    ports:
      - "8081:8081"  # Flink dashboard
    networks:
      - flybeta-network
    depends_on:
      - kafka
      - ml
    volumes:
      - flags-data:/opt/flags

  # ============================
  #  WhatsApp Bot
  # ============================
  whatsapp-bot:
    image: flybeta-whatsapp-bot
    build:
      context: ./bot
      dockerfile: whatsapp_bot.dockerfile
    container_name: whatsapp-bot
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - "NODE_ENV=development"
    networks:
      - flybeta-network
    depends_on:
      - backend
      - cloudsql-proxy
      - redis

  # ============================
  #  Ngrok Tunnel
  # ============================
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    env_file:
      - .env
    restart: unless-stopped
    command: http whatsapp-bot:${WHATSAPP_BOT_PORT}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    ports:
      - "4040:4040"  # Ngrok web interface
    networks:
      - flybeta-network
    depends_on:
      - whatsapp-bot

    # ===========================
    # Redis
    # ===========================
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - flybeta-network

volumes:
  kafka-data:
  flags-data:

networks:
  flybeta-network:
