services:

  # Node.js backend
  backend:
    image: flybeta-backend
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    environment:
      - "NODE_ENV=development"
    networks:
      - flybeta-network
    depends_on:
      - kafka
      - kafka-ui

  # Kafka broker
  kafka:
    image: apache/kafka:4.1.0
    container_name: kafka
    user: root
    ports:
      - "9092:9092"      # internal listener
      - "29092:29092"    # external listener (for your Node.js)
      - "9093:9093"      # controller
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LOG_DIRS: "/kafka-logs"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - flybeta-data:/kafka-logs
    networks:
      - flybeta-network

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"  # access UI in browser
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""  # empty because KRaft mode
    depends_on:
      - kafka
    networks:
      - flybeta-network

    # ML FastAPI service
  ml:
    image: flybeta-ml
    build:
      context: ./ml
      dockerfile: dockerfile
    container_name: ml
    ports:
      - "6000:6000"
    networks:
      - flybeta-network
    depends_on:
      - kafka
      - backend

  # Flink service
  flink:
    image: apache/flink:1.18-scala_2.12
    build:
      context: ./flink
      dockerfile: dockerfile
    container_name: flink
    ports:
      - "8081:8081"  # Flink dashboard
    networks:
      - flybeta-network
    depends_on:
      - kafka
      - ml

volumes:
  flybeta-data:

networks:
  flybeta-network:
